package money

import (
	"encoding/json"
	"errors"
	"strings"
)

// Currency represents money currency information required for formatting.
type Currency struct {
	Code     string
	Fraction int
	Grapheme string
	Template string
	Decimal  string
	Thousand string
}

// currencies represents a collection of currency.
var currencies = map[string]*Currency{
	"AED": {Decimal: ".", Thousand: ",", Code: "AED", Fraction: 2, Grapheme: ".\u062f.\u0625", Template: "1 $"},
	"AFN": {Decimal: ".", Thousand: ",", Code: "AFN", Fraction: 2, Grapheme: "\u060b", Template: "1 $"},
	"ALL": {Decimal: ".", Thousand: ",", Code: "ALL", Fraction: 2, Grapheme: "L", Template: "$1"},
	"AMD": {Decimal: ".", Thousand: ",", Code: "AMD", Fraction: 2, Grapheme: "\u0564\u0580.", Template: "1 $"},
	"ANG": {Decimal: ",", Thousand: ".", Code: "ANG", Fraction: 2, Grapheme: "\u0192", Template: "$1"},
	"AOA": {Decimal: ".", Thousand: ",", Code: "AOA", Fraction: 2, Grapheme: "Kz", Template: "1$"},
	"ARS": {Decimal: ".", Thousand: ",", Code: "ARS", Fraction: 2, Grapheme: "$", Template: "$1"},
	"AUD": {Decimal: ".", Thousand: ",", Code: "AUD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"AWG": {Decimal: ".", Thousand: ",", Code: "AWG", Fraction: 2, Grapheme: "\u0192", Template: "1$"},
	"AZN": {Decimal: ".", Thousand: ",", Code: "AZN", Fraction: 2, Grapheme: "\u20bc", Template: "$1"},
	"BAM": {Decimal: ".", Thousand: ",", Code: "BAM", Fraction: 2, Grapheme: "KM", Template: "$1"},
	"BBD": {Decimal: ".", Thousand: ",", Code: "BBD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"BDT": {Decimal: ".", Thousand: ",", Code: "BDT", Fraction: 2, Grapheme: "\u09f3", Template: "$1"},
	"BGN": {Decimal: ".", Thousand: ",", Code: "BGN", Fraction: 2, Grapheme: "\u043b\u0432", Template: "$1"},
	"BHD": {Decimal: ".", Thousand: ",", Code: "BHD", Fraction: 3, Grapheme: ".\u062f.\u0628", Template: "1 $"},
	"BIF": {Decimal: ".", Thousand: ",", Code: "BIF", Fraction: 0, Grapheme: "Fr", Template: "1$"},
	"BMD": {Decimal: ".", Thousand: ",", Code: "BMD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"BND": {Decimal: ".", Thousand: ",", Code: "BND", Fraction: 2, Grapheme: "$", Template: "$1"},
	"BOB": {Decimal: ".", Thousand: ",", Code: "BOB", Fraction: 2, Grapheme: "Bs.", Template: "$1"},
	"BRL": {Decimal: ".", Thousand: ",", Code: "BRL", Fraction: 2, Grapheme: "R$", Template: "$1"},
	"BSD": {Decimal: ".", Thousand: ",", Code: "BSD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"BTN": {Decimal: ".", Thousand: ",", Code: "BTN", Fraction: 2, Grapheme: "Nu.", Template: "1$"},
	"BWP": {Decimal: ".", Thousand: ",", Code: "BWP", Fraction: 2, Grapheme: "P", Template: "$1"},
	"BYN": {Decimal: ",", Thousand: " ", Code: "BYN", Fraction: 2, Grapheme: "p.", Template: "1 $"},
	"BYR": {Decimal: ",", Thousand: " ", Code: "BYR", Fraction: 0, Grapheme: "p.", Template: "1 $"},
	"BZD": {Decimal: ".", Thousand: ",", Code: "BZD", Fraction: 2, Grapheme: "BZ$", Template: "$1"},
	"CAD": {Decimal: ".", Thousand: ",", Code: "CAD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"CDF": {Decimal: ".", Thousand: ",", Code: "CDF", Fraction: 2, Grapheme: "FC", Template: "1$"},
	"CHF": {Decimal: ".", Thousand: ",", Code: "CHF", Fraction: 2, Grapheme: "CHF", Template: "1 $"},
	"CLF": {Decimal: ",", Thousand: ".", Code: "CLF", Fraction: 4, Grapheme: "UF", Template: "$1"},
	"CLP": {Decimal: ",", Thousand: ".", Code: "CLP", Fraction: 0, Grapheme: "$", Template: "$1"},
	"CNY": {Decimal: ".", Thousand: ",", Code: "CNY", Fraction: 2, Grapheme: "\u5143", Template: "1 $"},
	"COP": {Decimal: ",", Thousand: ".", Code: "COP", Fraction: 2, Grapheme: "$", Template: "$1"},
	"CRC": {Decimal: ".", Thousand: ",", Code: "CRC", Fraction: 2, Grapheme: "\u20a1", Template: "$1"},
	"CUC": {Decimal: ".", Thousand: ",", Code: "CUC", Fraction: 2, Grapheme: "$", Template: "1$"},
	"CUP": {Decimal: ".", Thousand: ",", Code: "CUP", Fraction: 2, Grapheme: "$MN", Template: "$1"},
	"CVE": {Decimal: ".", Thousand: ",", Code: "CVE", Fraction: 2, Grapheme: "$", Template: "1$"},
	"CZK": {Decimal: ".", Thousand: ",", Code: "CZK", Fraction: 2, Grapheme: "K\u010d", Template: "1 $"},
	"DJF": {Decimal: ".", Thousand: ",", Code: "DJF", Fraction: 0, Grapheme: "Fdj", Template: "1 $"},
	"DKK": {Decimal: ".", Thousand: ",", Code: "DKK", Fraction: 2, Grapheme: "kr", Template: "1 $"},
	"DOP": {Decimal: ".", Thousand: ",", Code: "DOP", Fraction: 2, Grapheme: "RD$", Template: "$1"},
	"DZD": {Decimal: ".", Thousand: ",", Code: "DZD", Fraction: 2, Grapheme: ".\u062f.\u062c", Template: "1 $"},
	"EEK": {Decimal: ".", Thousand: ",", Code: "EEK", Fraction: 2, Grapheme: "kr", Template: "$1"},
	"EGP": {Decimal: ".", Thousand: ",", Code: "EGP", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"ERN": {Decimal: ".", Thousand: ",", Code: "ERN", Fraction: 2, Grapheme: "Nfk", Template: "1 $"},
	"ETB": {Decimal: ".", Thousand: ",", Code: "ETB", Fraction: 2, Grapheme: "Br", Template: "1 $"},
	"EUR": {Decimal: ".", Thousand: ",", Code: "EUR", Fraction: 2, Grapheme: "\u20ac", Template: "$1"},
	"FJD": {Decimal: ".", Thousand: ",", Code: "FJD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"FKP": {Decimal: ".", Thousand: ",", Code: "FKP", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"GBP": {Decimal: ".", Thousand: ",", Code: "GBP", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"GEL": {Decimal: ".", Thousand: ",", Code: "GEL", Fraction: 2, Grapheme: "\u10da", Template: "1 $"},
	"GGP": {Decimal: ".", Thousand: ",", Code: "GGP", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"GHC": {Decimal: ".", Thousand: ",", Code: "GHC", Fraction: 2, Grapheme: "\u00a2", Template: "$1"},
	"GHS": {Decimal: ".", Thousand: ",", Code: "GHS", Fraction: 2, Grapheme: "\u20b5", Template: "$1"},
	"GIP": {Decimal: ".", Thousand: ",", Code: "GIP", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"GMD": {Decimal: ".", Thousand: ",", Code: "GMD", Fraction: 2, Grapheme: "D", Template: "1 $"},
	"GNF": {Decimal: ".", Thousand: ",", Code: "GNF", Fraction: 0, Grapheme: "FG", Template: "1 $"},
	"GTQ": {Decimal: ".", Thousand: ",", Code: "GTQ", Fraction: 2, Grapheme: "Q", Template: "$1"},
	"GYD": {Decimal: ".", Thousand: ",", Code: "GYD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"HKD": {Decimal: ".", Thousand: ",", Code: "HKD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"HNL": {Decimal: ".", Thousand: ",", Code: "HNL", Fraction: 2, Grapheme: "L", Template: "$1"},
	"HRK": {Decimal: ",", Thousand: ".", Code: "HRK", Fraction: 2, Grapheme: "kn", Template: "1 $"},
	"HTG": {Decimal: ",", Thousand: ".", Code: "HTG", Fraction: 2, Grapheme: "G", Template: "1 $"},
	"HUF": {Decimal: ".", Thousand: ",", Code: "HUF", Fraction: 0, Grapheme: "Ft", Template: "$1"},
	"IDR": {Decimal: ".", Thousand: ",", Code: "IDR", Fraction: 2, Grapheme: "Rp", Template: "$1"},
	"ILS": {Decimal: ".", Thousand: ",", Code: "ILS", Fraction: 2, Grapheme: "\u20aa", Template: "$1"},
	"IMP": {Decimal: ".", Thousand: ",", Code: "IMP", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"INR": {Decimal: ".", Thousand: ",", Code: "INR", Fraction: 2, Grapheme: "\u20b9", Template: "$1"},
	"IQD": {Decimal: ".", Thousand: ",", Code: "IQD", Fraction: 3, Grapheme: ".\u062f.\u0639", Template: "1 $"},
	"IRR": {Decimal: ".", Thousand: ",", Code: "IRR", Fraction: 2, Grapheme: "\ufdfc", Template: "1 $"},
	"ISK": {Decimal: ",", Thousand: ".", Code: "ISK", Fraction: 0, Grapheme: "kr", Template: "$1"},
	"JEP": {Decimal: ".", Thousand: ",", Code: "JEP", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"JMD": {Decimal: ".", Thousand: ",", Code: "JMD", Fraction: 2, Grapheme: "J$", Template: "$1"},
	"JOD": {Decimal: ".", Thousand: ",", Code: "JOD", Fraction: 3, Grapheme: ".\u062f.\u0625", Template: "1 $"},
	"JPY": {Decimal: ".", Thousand: ",", Code: "JPY", Fraction: 0, Grapheme: "\u00a5", Template: "$1"},
	"KES": {Decimal: ".", Thousand: ",", Code: "KES", Fraction: 2, Grapheme: "KSh", Template: "$1"},
	"KGS": {Decimal: ".", Thousand: ",", Code: "KGS", Fraction: 2, Grapheme: "\u0441\u043e\u043c", Template: "$1"},
	"KHR": {Decimal: ".", Thousand: ",", Code: "KHR", Fraction: 2, Grapheme: "\u17db", Template: "$1"},
	"KMF": {Decimal: ".", Thousand: ",", Code: "KMF", Fraction: 0, Grapheme: "CF", Template: "$1"},
	"KPW": {Decimal: ".", Thousand: ",", Code: "KPW", Fraction: 0, Grapheme: "\u20a9", Template: "$1"},
	"KRW": {Decimal: ".", Thousand: ",", Code: "KRW", Fraction: 0, Grapheme: "\u20a9", Template: "$1"},
	"KWD": {Decimal: ".", Thousand: ",", Code: "KWD", Fraction: 3, Grapheme: ".\u062f.\u0643", Template: "1 $"},
	"KYD": {Decimal: ".", Thousand: ",", Code: "KYD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"KZT": {Decimal: ".", Thousand: ",", Code: "KZT", Fraction: 2, Grapheme: "\u20b8", Template: "$1"},
	"LAK": {Decimal: ".", Thousand: ",", Code: "LAK", Fraction: 2, Grapheme: "\u20ad", Template: "$1"},
	"LBP": {Decimal: ".", Thousand: ",", Code: "LBP", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"LKR": {Decimal: ".", Thousand: ",", Code: "LKR", Fraction: 2, Grapheme: "\u20a8", Template: "$1"},
	"LRD": {Decimal: ".", Thousand: ",", Code: "LRD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"LSL": {Decimal: ".", Thousand: ",", Code: "LSL", Fraction: 2, Grapheme: "L", Template: "$1"},
	"LTL": {Decimal: ".", Thousand: ",", Code: "LTL", Fraction: 2, Grapheme: "Lt", Template: "$1"},
	"LVL": {Decimal: ".", Thousand: ",", Code: "LVL", Fraction: 2, Grapheme: "Ls", Template: "1 $"},
	"LYD": {Decimal: ".", Thousand: ",", Code: "LYD", Fraction: 3, Grapheme: ".\u062f.\u0644", Template: "1 $"},
	"MAD": {Decimal: ".", Thousand: ",", Code: "MAD", Fraction: 2, Grapheme: ".\u062f.\u0645", Template: "1 $"},
	"MDL": {Decimal: ".", Thousand: ",", Code: "MDL", Fraction: 2, Grapheme: "lei", Template: "1 $"},
	"MKD": {Decimal: ".", Thousand: ",", Code: "MKD", Fraction: 2, Grapheme: "\u0434\u0435\u043d", Template: "$1"},
	"MMK": {Decimal: ".", Thousand: ",", Code: "MMK", Fraction: 2, Grapheme: "K", Template: "$1"},
	"MNT": {Decimal: ".", Thousand: ",", Code: "MNT", Fraction: 2, Grapheme: "\u20ae", Template: "$1"},
	"MOP": {Decimal: ".", Thousand: ",", Code: "MOP", Fraction: 2, Grapheme: "P", Template: "1 $"},
	"MUR": {Decimal: ".", Thousand: ",", Code: "MUR", Fraction: 2, Grapheme: "\u20a8", Template: "$1"},
	"MVR": {Decimal: ".", Thousand: ",", Code: "MVR", Fraction: 2, Grapheme: "MVR", Template: "1 $"},
	"MWK": {Decimal: ".", Thousand: ",", Code: "MWK", Fraction: 2, Grapheme: "MK", Template: "$1"},
	"MXN": {Decimal: ".", Thousand: ",", Code: "MXN", Fraction: 2, Grapheme: "$", Template: "$1"},
	"MYR": {Decimal: ".", Thousand: ",", Code: "MYR", Fraction: 2, Grapheme: "RM", Template: "$1"},
	"MZN": {Decimal: ".", Thousand: ",", Code: "MZN", Fraction: 2, Grapheme: "MT", Template: "$1"},
	"NAD": {Decimal: ".", Thousand: ",", Code: "NAD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"NGN": {Decimal: ".", Thousand: ",", Code: "NGN", Fraction: 2, Grapheme: "\u20a6", Template: "$1"},
	"NIO": {Decimal: ".", Thousand: ",", Code: "NIO", Fraction: 2, Grapheme: "C$", Template: "$1"},
	"NOK": {Decimal: ".", Thousand: ",", Code: "NOK", Fraction: 2, Grapheme: "kr", Template: "1 $"},
	"NPR": {Decimal: ".", Thousand: ",", Code: "NPR", Fraction: 2, Grapheme: "\u20a8", Template: "$1"},
	"NZD": {Decimal: ".", Thousand: ",", Code: "NZD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"OMR": {Decimal: ".", Thousand: ",", Code: "OMR", Fraction: 3, Grapheme: "\ufdfc", Template: "1 $"},
	"PAB": {Decimal: ".", Thousand: ",", Code: "PAB", Fraction: 2, Grapheme: "B/.", Template: "$1"},
	"PEN": {Decimal: ".", Thousand: ",", Code: "PEN", Fraction: 2, Grapheme: "S/", Template: "$1"},
	"PGK": {Decimal: ".", Thousand: ",", Code: "PGK", Fraction: 2, Grapheme: "K", Template: "1 $"},
	"PHP": {Decimal: ".", Thousand: ",", Code: "PHP", Fraction: 2, Grapheme: "\u20b1", Template: "$1"},
	"PKR": {Decimal: ".", Thousand: ",", Code: "PKR", Fraction: 2, Grapheme: "\u20a8", Template: "$1"},
	"PLN": {Decimal: ".", Thousand: ",", Code: "PLN", Fraction: 2, Grapheme: "z\u0142", Template: "1 $"},
	"PYG": {Decimal: ".", Thousand: ",", Code: "PYG", Fraction: 0, Grapheme: "Gs", Template: "1$"},
	"QAR": {Decimal: ".", Thousand: ",", Code: "QAR", Fraction: 2, Grapheme: "\ufdfc", Template: "1 $"},
	"RON": {Decimal: ".", Thousand: ",", Code: "RON", Fraction: 2, Grapheme: "lei", Template: "$1"},
	"RSD": {Decimal: ".", Thousand: ",", Code: "RSD", Fraction: 2, Grapheme: "\u0414\u0438\u043d.", Template: "$1"},
	"RUB": {Decimal: ".", Thousand: ",", Code: "RUB", Fraction: 2, Grapheme: "\u20bd", Template: "1 $"},
	"RUR": {Decimal: ".", Thousand: ",", Code: "RUR", Fraction: 2, Grapheme: "\u20bd", Template: "1 $"},
	"RWF": {Decimal: ".", Thousand: ",", Code: "RWF", Fraction: 0, Grapheme: "FRw", Template: "1 $"},
	"SAR": {Decimal: ".", Thousand: ",", Code: "SAR", Fraction: 2, Grapheme: "\ufdfc", Template: "1 $"},
	"SBD": {Decimal: ".", Thousand: ",", Code: "SBD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"SCR": {Decimal: ".", Thousand: ",", Code: "SCR", Fraction: 2, Grapheme: "\u20a8", Template: "$1"},
	"SDG": {Decimal: ".", Thousand: ",", Code: "SDG", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"SEK": {Decimal: ".", Thousand: ",", Code: "SEK", Fraction: 2, Grapheme: "kr", Template: "1 $"},
	"SGD": {Decimal: ".", Thousand: ",", Code: "SGD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"SHP": {Decimal: ".", Thousand: ",", Code: "SHP", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"SKK": {Decimal: ".", Thousand: ",", Code: "SKK", Fraction: 2, Grapheme: "Sk", Template: "$1"},
	"SLL": {Decimal: ".", Thousand: ",", Code: "SLL", Fraction: 2, Grapheme: "Le", Template: "1 $"},
	"SOS": {Decimal: ".", Thousand: ",", Code: "SOS", Fraction: 2, Grapheme: "Sh", Template: "1 $"},
	"SRD": {Decimal: ".", Thousand: ",", Code: "SRD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"SSP": {Decimal: ".", Thousand: ",", Code: "SSP", Fraction: 2, Grapheme: "\u00a3", Template: "1 $"},
	"STD": {Decimal: ".", Thousand: ",", Code: "STD", Fraction: 2, Grapheme: "Db", Template: "1 $"},
	"SVC": {Decimal: ".", Thousand: ",", Code: "SVC", Fraction: 2, Grapheme: "\u20a1", Template: "$1"},
	"SYP": {Decimal: ".", Thousand: ",", Code: "SYP", Fraction: 2, Grapheme: "\u00a3", Template: "1 $"},
	"SZL": {Decimal: ".", Thousand: ",", Code: "SZL", Fraction: 2, Grapheme: "\u00a3", Template: "$1"},
	"THB": {Decimal: ".", Thousand: ",", Code: "THB", Fraction: 2, Grapheme: "\u0e3f", Template: "$1"},
	"TJS": {Decimal: ".", Thousand: ",", Code: "TJS", Fraction: 2, Grapheme: "SM", Template: "1 $"},
	"TMT": {Decimal: ".", Thousand: ",", Code: "TMT", Fraction: 2, Grapheme: "T", Template: "1 $"},
	"TND": {Decimal: ".", Thousand: ",", Code: "TND", Fraction: 3, Grapheme: ".\u062f.\u062a", Template: "1 $"},
	"TOP": {Decimal: ".", Thousand: ",", Code: "TOP", Fraction: 2, Grapheme: "T$", Template: "$1"},
	"TRL": {Decimal: ".", Thousand: ",", Code: "TRL", Fraction: 2, Grapheme: "\u20a4", Template: "$1"},
	"TRY": {Decimal: ".", Thousand: ",", Code: "TRY", Fraction: 2, Grapheme: "\u20ba", Template: "$1"},
	"TTD": {Decimal: ".", Thousand: ",", Code: "TTD", Fraction: 2, Grapheme: "TT$", Template: "$1"},
	"TWD": {Decimal: ".", Thousand: ",", Code: "TWD", Fraction: 0, Grapheme: "NT$", Template: "$1"},
	"TZS": {Decimal: ".", Thousand: ",", Code: "TZS", Fraction: 0, Grapheme: "TSh", Template: "$1"},
	"UAH": {Decimal: ".", Thousand: ",", Code: "UAH", Fraction: 2, Grapheme: "\u20b4", Template: "1 $"},
	"UGX": {Decimal: ".", Thousand: ",", Code: "UGX", Fraction: 0, Grapheme: "USh", Template: "1 $"},
	"USD": {Decimal: ".", Thousand: ",", Code: "USD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"UYU": {Decimal: ".", Thousand: ",", Code: "UYU", Fraction: 2, Grapheme: "$U", Template: "$1"},
	"UZS": {Decimal: ".", Thousand: ",", Code: "UZS", Fraction: 2, Grapheme: "so\u2019m", Template: "$1"},
	"VEF": {Decimal: ".", Thousand: ",", Code: "VEF", Fraction: 2, Grapheme: "Bs", Template: "$1"},
	"VND": {Decimal: ".", Thousand: ",", Code: "VND", Fraction: 0, Grapheme: "\u20ab", Template: "1 $"},
	"VUV": {Decimal: ".", Thousand: ",", Code: "VUV", Fraction: 0, Grapheme: "Vt", Template: "$1"},
	"WST": {Decimal: ".", Thousand: ",", Code: "WST", Fraction: 2, Grapheme: "T", Template: "1 $"},
	"XAF": {Decimal: ".", Thousand: ",", Code: "XAF", Fraction: 0, Grapheme: "Fr", Template: "1 $"},
	"XAG": {Decimal: ".", Thousand: ",", Code: "XAG", Fraction: 0, Grapheme: "oz t", Template: "1 $"},
	"XAU": {Decimal: ".", Thousand: ",", Code: "XAU", Fraction: 0, Grapheme: "oz t", Template: "1 $"},
	"XCD": {Decimal: ".", Thousand: ",", Code: "XCD", Fraction: 2, Grapheme: "$", Template: "$1"},
	"XDR": {Decimal: ".", Thousand: ",", Code: "XDR", Fraction: 0, Grapheme: "SDR", Template: "1 $"},
	"YER": {Decimal: ".", Thousand: ",", Code: "YER", Fraction: 2, Grapheme: "\ufdfc", Template: "1 $"},
	"ZAR": {Decimal: ".", Thousand: ",", Code: "ZAR", Fraction: 2, Grapheme: "R", Template: "$1"},
	"ZMW": {Decimal: ".", Thousand: ",", Code: "ZMW", Fraction: 2, Grapheme: "ZK", Template: "$1"},
	"ZWD": {Decimal: ".", Thousand: ",", Code: "ZWD", Fraction: 2, Grapheme: "Z$", Template: "$1"},

	// https://github.com/yonilevy/crypto-currency-symbols
	"BTC":  {Decimal: ".", Thousand: ",", Code: "BTC", Fraction: 8, Grapheme: "\u0e3f", Template: "$1"},
	"ETH":  {Decimal: ".", Thousand: ",", Code: "ETH", Fraction: 8, Grapheme: "\u039e", Template: "$1"},
	"USDT": {Decimal: ".", Thousand: ",", Code: "USDT", Fraction: 2, Grapheme: "₮", Template: "$1"},
	"XRP":  {Decimal: ".", Thousand: ",", Code: "XRP", Fraction: 6, Grapheme: "✕", Template: "$1"},
	"LTC":  {Decimal: ".", Thousand: ",", Code: "LTC", Fraction: 8, Grapheme: "Ł", Template: "$1"},

	// from binance pairs
	"DASH":    {Decimal: ".", Thousand: ",", Code: "DASH", Fraction: 8, Grapheme: "DASH", Template: "$1"},
	"OGN":     {Decimal: ".", Thousand: ",", Code: "OGN", Fraction: 8, Grapheme: "OGN", Template: "$1"},
	"BTCUP":   {Decimal: ".", Thousand: ",", Code: "BTCUP", Fraction: 8, Grapheme: "BTCUP", Template: "$1"},
	"RLC":     {Decimal: ".", Thousand: ",", Code: "RLC", Fraction: 8, Grapheme: "RLC", Template: "$1"},
	"PPT":     {Decimal: ".", Thousand: ",", Code: "PPT", Fraction: 8, Grapheme: "PPT", Template: "$1"},
	"ZIL":     {Decimal: ".", Thousand: ",", Code: "ZIL", Fraction: 8, Grapheme: "ZIL", Template: "$1"},
	"ONG":     {Decimal: ".", Thousand: ",", Code: "ONG", Fraction: 8, Grapheme: "ONG", Template: "$1"},
	"KAVA":    {Decimal: ".", Thousand: ",", Code: "KAVA", Fraction: 8, Grapheme: "KAVA", Template: "$1"},
	"BTS":     {Decimal: ".", Thousand: ",", Code: "BTS", Fraction: 8, Grapheme: "BTS", Template: "$1"},
	"NXS":     {Decimal: ".", Thousand: ",", Code: "NXS", Fraction: 8, Grapheme: "NXS", Template: "$1"},
	"ENG":     {Decimal: ".", Thousand: ",", Code: "ENG", Fraction: 8, Grapheme: "ENG", Template: "$1"},
	"GTO":     {Decimal: ".", Thousand: ",", Code: "GTO", Fraction: 8, Grapheme: "GTO", Template: "$1"},
	"AION":    {Decimal: ".", Thousand: ",", Code: "AION", Fraction: 8, Grapheme: "AION", Template: "$1"},
	"BAND":    {Decimal: ".", Thousand: ",", Code: "BAND", Fraction: 8, Grapheme: "BAND", Template: "$1"},
	"ONT":     {Decimal: ".", Thousand: ",", Code: "ONT", Fraction: 8, Grapheme: "ONT", Template: "$1"},
	"LRC":     {Decimal: ".", Thousand: ",", Code: "LRC", Fraction: 8, Grapheme: "LRC", Template: "$1"},
	"REP":     {Decimal: ".", Thousand: ",", Code: "REP", Fraction: 8, Grapheme: "REP", Template: "$1"},
	"ONE":     {Decimal: ".", Thousand: ",", Code: "ONE", Fraction: 8, Grapheme: "ONE", Template: "$1"},
	"FET":     {Decimal: ".", Thousand: ",", Code: "FET", Fraction: 8, Grapheme: "FET", Template: "$1"},
	"SKY":     {Decimal: ".", Thousand: ",", Code: "SKY", Fraction: 8, Grapheme: "SKY", Template: "$1"},
	"KMD":     {Decimal: ".", Thousand: ",", Code: "KMD", Fraction: 8, Grapheme: "KMD", Template: "$1"},
	"NAS":     {Decimal: ".", Thousand: ",", Code: "NAS", Fraction: 8, Grapheme: "NAS", Template: "$1"},
	"SOL":     {Decimal: ".", Thousand: ",", Code: "SOL", Fraction: 8, Grapheme: "SOL", Template: "$1"},
	"GNT":     {Decimal: ".", Thousand: ",", Code: "GNT", Fraction: 8, Grapheme: "GNT", Template: "$1"},
	"ADX":     {Decimal: ".", Thousand: ",", Code: "ADX", Fraction: 8, Grapheme: "ADX", Template: "$1"},
	"VIBE":    {Decimal: ".", Thousand: ",", Code: "VIBE", Fraction: 8, Grapheme: "VIBE", Template: "$1"},
	"BUSD":    {Decimal: ".", Thousand: ",", Code: "BUSD", Fraction: 8, Grapheme: "BUSD", Template: "$1"},
	"DGB":     {Decimal: ".", Thousand: ",", Code: "DGB", Fraction: 8, Grapheme: "DGB", Template: "$1"},
	"CVC":     {Decimal: ".", Thousand: ",", Code: "CVC", Fraction: 8, Grapheme: "CVC", Template: "$1"},
	"WAVES":   {Decimal: ".", Thousand: ",", Code: "WAVES", Fraction: 8, Grapheme: "WAVES", Template: "$1"},
	"WIN":     {Decimal: ".", Thousand: ",", Code: "WIN", Fraction: 8, Grapheme: "WIN", Template: "$1"},
	"MANA":    {Decimal: ".", Thousand: ",", Code: "MANA", Fraction: 8, Grapheme: "MANA", Template: "$1"},
	"QSP":     {Decimal: ".", Thousand: ",", Code: "QSP", Fraction: 8, Grapheme: "QSP", Template: "$1"},
	"ARDR":    {Decimal: ".", Thousand: ",", Code: "ARDR", Fraction: 8, Grapheme: "ARDR", Template: "$1"},
	"HOT":     {Decimal: ".", Thousand: ",", Code: "HOT", Fraction: 8, Grapheme: "HOT", Template: "$1"},
	"NAV":     {Decimal: ".", Thousand: ",", Code: "NAV", Fraction: 8, Grapheme: "NAV", Template: "$1"},
	"CHZ":     {Decimal: ".", Thousand: ",", Code: "CHZ", Fraction: 8, Grapheme: "CHZ", Template: "$1"},
	"MTH":     {Decimal: ".", Thousand: ",", Code: "MTH", Fraction: 8, Grapheme: "MTH", Template: "$1"},
	"FTT":     {Decimal: ".", Thousand: ",", Code: "FTT", Fraction: 8, Grapheme: "FTT", Template: "$1"},
	"BNB":     {Decimal: ".", Thousand: ",", Code: "BNB", Fraction: 8, Grapheme: "BNB", Template: "$1"},
	"INS":     {Decimal: ".", Thousand: ",", Code: "INS", Fraction: 8, Grapheme: "INS", Template: "$1"},
	"POA":     {Decimal: ".", Thousand: ",", Code: "POA", Fraction: 8, Grapheme: "POA", Template: "$1"},
	"DATA":    {Decimal: ".", Thousand: ",", Code: "DATA", Fraction: 8, Grapheme: "DATA", Template: "$1"},
	"EOS":     {Decimal: ".", Thousand: ",", Code: "EOS", Fraction: 8, Grapheme: "EOS", Template: "$1"},
	"ZEN":     {Decimal: ".", Thousand: ",", Code: "ZEN", Fraction: 8, Grapheme: "ZEN", Template: "$1"},
	"TCT":     {Decimal: ".", Thousand: ",", Code: "TCT", Fraction: 8, Grapheme: "TCT", Template: "$1"},
	"XZC":     {Decimal: ".", Thousand: ",", Code: "XZC", Fraction: 8, Grapheme: "XZC", Template: "$1"},
	"QTUM":    {Decimal: ".", Thousand: ",", Code: "QTUM", Fraction: 8, Grapheme: "QTUM", Template: "$1"},
	"TNB":     {Decimal: ".", Thousand: ",", Code: "TNB", Fraction: 8, Grapheme: "TNB", Template: "$1"},
	"PAX":     {Decimal: ".", Thousand: ",", Code: "PAX", Fraction: 8, Grapheme: "PAX", Template: "$1"},
	"BNT":     {Decimal: ".", Thousand: ",", Code: "BNT", Fraction: 8, Grapheme: "BNT", Template: "$1"},
	"SC":      {Decimal: ".", Thousand: ",", Code: "SC", Fraction: 8, Grapheme: "SC", Template: "$1"},
	"COTI":    {Decimal: ".", Thousand: ",", Code: "COTI", Fraction: 8, Grapheme: "COTI", Template: "$1"},
	"SNT":     {Decimal: ".", Thousand: ",", Code: "SNT", Fraction: 8, Grapheme: "SNT", Template: "$1"},
	"BLZ":     {Decimal: ".", Thousand: ",", Code: "BLZ", Fraction: 8, Grapheme: "BLZ", Template: "$1"},
	"TUSD":    {Decimal: ".", Thousand: ",", Code: "TUSD", Fraction: 8, Grapheme: "TUSD", Template: "$1"},
	"WTC":     {Decimal: ".", Thousand: ",", Code: "WTC", Fraction: 8, Grapheme: "WTC", Template: "$1"},
	"CHR":     {Decimal: ".", Thousand: ",", Code: "CHR", Fraction: 8, Grapheme: "CHR", Template: "$1"},
	"MTL":     {Decimal: ".", Thousand: ",", Code: "MTL", Fraction: 8, Grapheme: "MTL", Template: "$1"},
	"BCH":     {Decimal: ".", Thousand: ",", Code: "BCH", Fraction: 8, Grapheme: "BCH", Template: "$1"},
	"PHB":     {Decimal: ".", Thousand: ",", Code: "PHB", Fraction: 8, Grapheme: "PHB", Template: "$1"},
	"XEM":     {Decimal: ".", Thousand: ",", Code: "XEM", Fraction: 8, Grapheme: "XEM", Template: "$1"},
	"NULS":    {Decimal: ".", Thousand: ",", Code: "NULS", Fraction: 8, Grapheme: "NULS", Template: "$1"},
	"ERD":     {Decimal: ".", Thousand: ",", Code: "ERD", Fraction: 8, Grapheme: "ERD", Template: "$1"},
	"XTZ":     {Decimal: ".", Thousand: ",", Code: "XTZ", Fraction: 8, Grapheme: "XTZ", Template: "$1"},
	"GO":      {Decimal: ".", Thousand: ",", Code: "GO", Fraction: 8, Grapheme: "GO", Template: "$1"},
	"ARK":     {Decimal: ".", Thousand: ",", Code: "ARK", Fraction: 8, Grapheme: "ARK", Template: "$1"},
	"DCR":     {Decimal: ".", Thousand: ",", Code: "DCR", Fraction: 8, Grapheme: "DCR", Template: "$1"},
	"ICX":     {Decimal: ".", Thousand: ",", Code: "ICX", Fraction: 8, Grapheme: "ICX", Template: "$1"},
	"LOOM":    {Decimal: ".", Thousand: ",", Code: "LOOM", Fraction: 8, Grapheme: "LOOM", Template: "$1"},
	"DENT":    {Decimal: ".", Thousand: ",", Code: "DENT", Fraction: 8, Grapheme: "DENT", Template: "$1"},
	"BRD":     {Decimal: ".", Thousand: ",", Code: "BRD", Fraction: 8, Grapheme: "BRD", Template: "$1"},
	"RVN":     {Decimal: ".", Thousand: ",", Code: "RVN", Fraction: 8, Grapheme: "RVN", Template: "$1"},
	"CDT":     {Decimal: ".", Thousand: ",", Code: "CDT", Fraction: 8, Grapheme: "CDT", Template: "$1"},
	"STPT":    {Decimal: ".", Thousand: ",", Code: "STPT", Fraction: 8, Grapheme: "STPT", Template: "$1"},
	"COMP":    {Decimal: ".", Thousand: ",", Code: "COMP", Fraction: 8, Grapheme: "COMP", Template: "$1"},
	"CND":     {Decimal: ".", Thousand: ",", Code: "CND", Fraction: 8, Grapheme: "CND", Template: "$1"},
	"VITE":    {Decimal: ".", Thousand: ",", Code: "VITE", Fraction: 8, Grapheme: "VITE", Template: "$1"},
	"PIVX":    {Decimal: ".", Thousand: ",", Code: "PIVX", Fraction: 8, Grapheme: "PIVX", Template: "$1"},
	"BKRW":    {Decimal: ".", Thousand: ",", Code: "BKRW", Fraction: 8, Grapheme: "BKRW", Template: "$1"},
	"USDC":    {Decimal: ".", Thousand: ",", Code: "USDC", Fraction: 8, Grapheme: "USDC", Template: "$1"},
	"MCO":     {Decimal: ".", Thousand: ",", Code: "MCO", Fraction: 8, Grapheme: "MCO", Template: "$1"},
	"BQX":     {Decimal: ".", Thousand: ",", Code: "BQX", Fraction: 8, Grapheme: "BQX", Template: "$1"},
	"LEND":    {Decimal: ".", Thousand: ",", Code: "LEND", Fraction: 8, Grapheme: "LEND", Template: "$1"},
	"BAT":     {Decimal: ".", Thousand: ",", Code: "BAT", Fraction: 8, Grapheme: "BAT", Template: "$1"},
	"DUSK":    {Decimal: ".", Thousand: ",", Code: "DUSK", Fraction: 8, Grapheme: "DUSK", Template: "$1"},
	"BTG":     {Decimal: ".", Thousand: ",", Code: "BTG", Fraction: 8, Grapheme: "BTG", Template: "$1"},
	"ANKR":    {Decimal: ".", Thousand: ",", Code: "ANKR", Fraction: 8, Grapheme: "ANKR", Template: "$1"},
	"GXS":     {Decimal: ".", Thousand: ",", Code: "GXS", Fraction: 8, Grapheme: "GXS", Template: "$1"},
	"STORJ":   {Decimal: ".", Thousand: ",", Code: "STORJ", Fraction: 8, Grapheme: "STORJ", Template: "$1"},
	"AMB":     {Decimal: ".", Thousand: ",", Code: "AMB", Fraction: 8, Grapheme: "AMB", Template: "$1"},
	"CMT":     {Decimal: ".", Thousand: ",", Code: "CMT", Fraction: 8, Grapheme: "CMT", Template: "$1"},
	"RCN":     {Decimal: ".", Thousand: ",", Code: "RCN", Fraction: 8, Grapheme: "RCN", Template: "$1"},
	"LTO":     {Decimal: ".", Thousand: ",", Code: "LTO", Fraction: 8, Grapheme: "LTO", Template: "$1"},
	"EVX":     {Decimal: ".", Thousand: ",", Code: "EVX", Fraction: 8, Grapheme: "EVX", Template: "$1"},
	"NKN":     {Decimal: ".", Thousand: ",", Code: "NKN", Fraction: 8, Grapheme: "NKN", Template: "$1"},
	"POWR":    {Decimal: ".", Thousand: ",", Code: "POWR", Fraction: 8, Grapheme: "POWR", Template: "$1"},
	"ENJ":     {Decimal: ".", Thousand: ",", Code: "ENJ", Fraction: 8, Grapheme: "ENJ", Template: "$1"},
	"KNC":     {Decimal: ".", Thousand: ",", Code: "KNC", Fraction: 8, Grapheme: "KNC", Template: "$1"},
	"OAX":     {Decimal: ".", Thousand: ",", Code: "OAX", Fraction: 8, Grapheme: "OAX", Template: "$1"},
	"GAS":     {Decimal: ".", Thousand: ",", Code: "GAS", Fraction: 8, Grapheme: "GAS", Template: "$1"},
	"IDRT":    {Decimal: ".", Thousand: ",", Code: "IDRT", Fraction: 8, Grapheme: "IDRT", Template: "$1"},
	"OST":     {Decimal: ".", Thousand: ",", Code: "OST", Fraction: 8, Grapheme: "OST", Template: "$1"},
	"ELF":     {Decimal: ".", Thousand: ",", Code: "ELF", Fraction: 8, Grapheme: "ELF", Template: "$1"},
	"COCOS":   {Decimal: ".", Thousand: ",", Code: "COCOS", Fraction: 8, Grapheme: "COCOS", Template: "$1"},
	"IOTX":    {Decimal: ".", Thousand: ",", Code: "IOTX", Fraction: 8, Grapheme: "IOTX", Template: "$1"},
	"AGI":     {Decimal: ".", Thousand: ",", Code: "AGI", Fraction: 8, Grapheme: "AGI", Template: "$1"},
	"XLM":     {Decimal: ".", Thousand: ",", Code: "XLM", Fraction: 8, Grapheme: "XLM", Template: "$1"},
	"XMR":     {Decimal: ".", Thousand: ",", Code: "XMR", Fraction: 8, Grapheme: "XMR", Template: "$1"},
	"STEEM":   {Decimal: ".", Thousand: ",", Code: "STEEM", Fraction: 8, Grapheme: "STEEM", Template: "$1"},
	"PERL":    {Decimal: ".", Thousand: ",", Code: "PERL", Fraction: 8, Grapheme: "PERL", Template: "$1"},
	"TNT":     {Decimal: ".", Thousand: ",", Code: "TNT", Fraction: 8, Grapheme: "TNT", Template: "$1"},
	"GRS":     {Decimal: ".", Thousand: ",", Code: "GRS", Fraction: 8, Grapheme: "GRS", Template: "$1"},
	"ZRX":     {Decimal: ".", Thousand: ",", Code: "ZRX", Fraction: 8, Grapheme: "ZRX", Template: "$1"},
	"KEY":     {Decimal: ".", Thousand: ",", Code: "KEY", Fraction: 8, Grapheme: "KEY", Template: "$1"},
	"MITH":    {Decimal: ".", Thousand: ",", Code: "MITH", Fraction: 8, Grapheme: "MITH", Template: "$1"},
	"SYS":     {Decimal: ".", Thousand: ",", Code: "SYS", Fraction: 8, Grapheme: "SYS", Template: "$1"},
	"TROY":    {Decimal: ".", Thousand: ",", Code: "TROY", Fraction: 8, Grapheme: "TROY", Template: "$1"},
	"THETA":   {Decimal: ".", Thousand: ",", Code: "THETA", Fraction: 8, Grapheme: "THETA", Template: "$1"},
	"OMG":     {Decimal: ".", Thousand: ",", Code: "OMG", Fraction: 8, Grapheme: "OMG", Template: "$1"},
	"FTM":     {Decimal: ".", Thousand: ",", Code: "FTM", Fraction: 8, Grapheme: "FTM", Template: "$1"},
	"BEAM":    {Decimal: ".", Thousand: ",", Code: "BEAM", Fraction: 8, Grapheme: "BEAM", Template: "$1"},
	"NCASH":   {Decimal: ".", Thousand: ",", Code: "NCASH", Fraction: 8, Grapheme: "NCASH", Template: "$1"},
	"WABI":    {Decimal: ".", Thousand: ",", Code: "WABI", Fraction: 8, Grapheme: "WABI", Template: "$1"},
	"DOGE":    {Decimal: ".", Thousand: ",", Code: "DOGE", Fraction: 8, Grapheme: "DOGE", Template: "$1"},
	"ARPA":    {Decimal: ".", Thousand: ",", Code: "ARPA", Fraction: 8, Grapheme: "ARPA", Template: "$1"},
	"SNGLS":   {Decimal: ".", Thousand: ",", Code: "SNGLS", Fraction: 8, Grapheme: "SNGLS", Template: "$1"},
	"CELR":    {Decimal: ".", Thousand: ",", Code: "CELR", Fraction: 8, Grapheme: "CELR", Template: "$1"},
	"DOCK":    {Decimal: ".", Thousand: ",", Code: "DOCK", Fraction: 8, Grapheme: "DOCK", Template: "$1"},
	"HIVE":    {Decimal: ".", Thousand: ",", Code: "HIVE", Fraction: 8, Grapheme: "HIVE", Template: "$1"},
	"AST":     {Decimal: ".", Thousand: ",", Code: "AST", Fraction: 8, Grapheme: "AST", Template: "$1"},
	"DLT":     {Decimal: ".", Thousand: ",", Code: "DLT", Fraction: 8, Grapheme: "DLT", Template: "$1"},
	"DNT":     {Decimal: ".", Thousand: ",", Code: "DNT", Fraction: 8, Grapheme: "DNT", Template: "$1"},
	"TFUEL":   {Decimal: ".", Thousand: ",", Code: "TFUEL", Fraction: 8, Grapheme: "TFUEL", Template: "$1"},
	"DREP":    {Decimal: ".", Thousand: ",", Code: "DREP", Fraction: 8, Grapheme: "DREP", Template: "$1"},
	"GVT":     {Decimal: ".", Thousand: ",", Code: "GVT", Fraction: 8, Grapheme: "GVT", Template: "$1"},
	"STRAT":   {Decimal: ".", Thousand: ",", Code: "STRAT", Fraction: 8, Grapheme: "STRAT", Template: "$1"},
	"ADA":     {Decimal: ".", Thousand: ",", Code: "ADA", Fraction: 8, Grapheme: "ADA", Template: "$1"},
	"POE":     {Decimal: ".", Thousand: ",", Code: "POE", Fraction: 8, Grapheme: "POE", Template: "$1"},
	"ALGO":    {Decimal: ".", Thousand: ",", Code: "ALGO", Fraction: 8, Grapheme: "ALGO", Template: "$1"},
	"WAN":     {Decimal: ".", Thousand: ",", Code: "WAN", Fraction: 8, Grapheme: "WAN", Template: "$1"},
	"CTXC":    {Decimal: ".", Thousand: ",", Code: "CTXC", Fraction: 8, Grapheme: "CTXC", Template: "$1"},
	"BGBP":    {Decimal: ".", Thousand: ",", Code: "BGBP", Fraction: 8, Grapheme: "BGBP", Template: "$1"},
	"ZEC":     {Decimal: ".", Thousand: ",", Code: "ZEC", Fraction: 8, Grapheme: "ZEC", Template: "$1"},
	"NEO":     {Decimal: ".", Thousand: ",", Code: "NEO", Fraction: 8, Grapheme: "NEO", Template: "$1"},
	"FUEL":    {Decimal: ".", Thousand: ",", Code: "FUEL", Fraction: 8, Grapheme: "FUEL", Template: "$1"},
	"AE":      {Decimal: ".", Thousand: ",", Code: "AE", Fraction: 8, Grapheme: "AE", Template: "$1"},
	"ARN":     {Decimal: ".", Thousand: ",", Code: "ARN", Fraction: 8, Grapheme: "ARN", Template: "$1"},
	"FUN":     {Decimal: ".", Thousand: ",", Code: "FUN", Fraction: 8, Grapheme: "FUN", Template: "$1"},
	"QKC":     {Decimal: ".", Thousand: ",", Code: "QKC", Fraction: 8, Grapheme: "QKC", Template: "$1"},
	"WPR":     {Decimal: ".", Thousand: ",", Code: "WPR", Fraction: 8, Grapheme: "WPR", Template: "$1"},
	"MDT":     {Decimal: ".", Thousand: ",", Code: "MDT", Fraction: 8, Grapheme: "MDT", Template: "$1"},
	"PNT":     {Decimal: ".", Thousand: ",", Code: "PNT", Fraction: 8, Grapheme: "PNT", Template: "$1"},
	"MATIC":   {Decimal: ".", Thousand: ",", Code: "MATIC", Fraction: 8, Grapheme: "MATIC", Template: "$1"},
	"NEBL":    {Decimal: ".", Thousand: ",", Code: "NEBL", Fraction: 8, Grapheme: "NEBL", Template: "$1"},
	"NANO":    {Decimal: ".", Thousand: ",", Code: "NANO", Fraction: 8, Grapheme: "NANO", Template: "$1"},
	"POLY":    {Decimal: ".", Thousand: ",", Code: "POLY", Fraction: 8, Grapheme: "POLY", Template: "$1"},
	"COS":     {Decimal: ".", Thousand: ",", Code: "COS", Fraction: 8, Grapheme: "COS", Template: "$1"},
	"SNM":     {Decimal: ".", Thousand: ",", Code: "SNM", Fraction: 8, Grapheme: "SNM", Template: "$1"},
	"VIB":     {Decimal: ".", Thousand: ",", Code: "VIB", Fraction: 8, Grapheme: "VIB", Template: "$1"},
	"REQ":     {Decimal: ".", Thousand: ",", Code: "REQ", Fraction: 8, Grapheme: "REQ", Template: "$1"},
	"TRX":     {Decimal: ".", Thousand: ",", Code: "TRX", Fraction: 8, Grapheme: "TRX", Template: "$1"},
	"ATOM":    {Decimal: ".", Thousand: ",", Code: "ATOM", Fraction: 8, Grapheme: "ATOM", Template: "$1"},
	"CTSI":    {Decimal: ".", Thousand: ",", Code: "CTSI", Fraction: 8, Grapheme: "CTSI", Template: "$1"},
	"BTT":     {Decimal: ".", Thousand: ",", Code: "BTT", Fraction: 8, Grapheme: "BTT", Template: "$1"},
	"MDA":     {Decimal: ".", Thousand: ",", Code: "MDA", Fraction: 8, Grapheme: "MDA", Template: "$1"},
	"LUN":     {Decimal: ".", Thousand: ",", Code: "LUN", Fraction: 8, Grapheme: "LUN", Template: "$1"},
	"MBL":     {Decimal: ".", Thousand: ",", Code: "MBL", Fraction: 8, Grapheme: "MBL", Template: "$1"},
	"BTCDOWN": {Decimal: ".", Thousand: ",", Code: "BTCDOWN", Fraction: 8, Grapheme: "BTCDOWN", Template: "$1"},
	"BCPT":    {Decimal: ".", Thousand: ",", Code: "BCPT", Fraction: 8, Grapheme: "BCPT", Template: "$1"},
	"BCD":     {Decimal: ".", Thousand: ",", Code: "BCD", Fraction: 8, Grapheme: "BCD", Template: "$1"},
	"VIA":     {Decimal: ".", Thousand: ",", Code: "VIA", Fraction: 8, Grapheme: "VIA", Template: "$1"},
	"ETC":     {Decimal: ".", Thousand: ",", Code: "ETC", Fraction: 8, Grapheme: "ETC", Template: "$1"},
	"HC":      {Decimal: ".", Thousand: ",", Code: "HC", Fraction: 8, Grapheme: "HC", Template: "$1"},
	"STMX":    {Decimal: ".", Thousand: ",", Code: "STMX", Fraction: 8, Grapheme: "STMX", Template: "$1"},
	"RDN":     {Decimal: ".", Thousand: ",", Code: "RDN", Fraction: 8, Grapheme: "RDN", Template: "$1"},
	"MFT":     {Decimal: ".", Thousand: ",", Code: "MFT", Fraction: 8, Grapheme: "MFT", Template: "$1"},
	"LINK":    {Decimal: ".", Thousand: ",", Code: "LINK", Fraction: 8, Grapheme: "LINK", Template: "$1"},
	"IQ":      {Decimal: ".", Thousand: ",", Code: "IQ", Fraction: 8, Grapheme: "IQ", Template: "$1"},
	"VET":     {Decimal: ".", Thousand: ",", Code: "VET", Fraction: 8, Grapheme: "VET", Template: "$1"},
	"TOMO":    {Decimal: ".", Thousand: ",", Code: "TOMO", Fraction: 8, Grapheme: "TOMO", Template: "$1"},
	"HBAR":    {Decimal: ".", Thousand: ",", Code: "HBAR", Fraction: 8, Grapheme: "HBAR", Template: "$1"},
	"IOST":    {Decimal: ".", Thousand: ",", Code: "IOST", Fraction: 8, Grapheme: "IOST", Template: "$1"},
	"YOYO":    {Decimal: ".", Thousand: ",", Code: "YOYO", Fraction: 8, Grapheme: "YOYO", Template: "$1"},
	"LSK":     {Decimal: ".", Thousand: ",", Code: "LSK", Fraction: 8, Grapheme: "LSK", Template: "$1"},
	"APPC":    {Decimal: ".", Thousand: ",", Code: "APPC", Fraction: 8, Grapheme: "APPC", Template: "$1"},
	"IOTA":    {Decimal: ".", Thousand: ",", Code: "IOTA", Fraction: 8, Grapheme: "IOTA", Template: "$1"},
	"XVG":     {Decimal: ".", Thousand: ",", Code: "XVG", Fraction: 8, Grapheme: "XVG", Template: "$1"},
	"QLC":     {Decimal: ".", Thousand: ",", Code: "QLC", Fraction: 8, Grapheme: "QLC", Template: "$1"},
	"REN":     {Decimal: ".", Thousand: ",", Code: "REN", Fraction: 8, Grapheme: "REN", Template: "$1"},
	"WRX":     {Decimal: ".", Thousand: ",", Code: "WRX", Fraction: 8, Grapheme: "WRX", Template: "$1"},
	"STX":     {Decimal: ".", Thousand: ",", Code: "STX", Fraction: 8, Grapheme: "STX", Template: "$1"},
	"NPXS":    {Decimal: ".", Thousand: ",", Code: "NPXS", Fraction: 8, Grapheme: "NPXS", Template: "$1"},
}

// AddCurrency lets you insert or update currency in currencies list.
func AddCurrency(Code, Grapheme, Template, Decimal, Thousand string, Fraction int) *Currency {
	currencies[Code] = &Currency{
		Code:     Code,
		Grapheme: Grapheme,
		Template: Template,
		Decimal:  Decimal,
		Thousand: Thousand,
		Fraction: Fraction,
	}

	return currencies[Code]
}

func newCurrency(code string) *Currency {
	return &Currency{Code: strings.ToUpper(code)}
}

// GetCurrency returns the currency given the code.
func GetCurrency(code string) *Currency {
	return currencies[code]
}

// Formatter returns currency formatter representing
// used currency structure.
func (c *Currency) Formatter() *Formatter {
	return &Formatter{
		Fraction: c.Fraction,
		Decimal:  c.Decimal,
		Thousand: c.Thousand,
		Grapheme: c.Grapheme,
		Template: c.Template,
	}
}

// getDefault represent default currency if currency is not found in currencies list.
// Grapheme and Code fields will be changed by currency code.
func (c *Currency) getDefault() *Currency {
	return &Currency{Decimal: ".", Thousand: ",", Code: c.Code, Fraction: 2, Grapheme: c.Code, Template: "1$"}
}

// get extended currency using currencies list.
func (c *Currency) get() *Currency {
	if curr, ok := currencies[c.Code]; ok {
		return curr
	}

	return c.getDefault()
}

func (c *Currency) equals(oc *Currency) bool {
	return c.Code == oc.Code
}

func (c *Currency) UnmarshalJSON(b []byte) error {
	var code string
	if err := json.Unmarshal(b, &code); err != nil {
		return err
	}

	*c = *GetCurrency(strings.ToUpper(code))
	if c == nil {
		return errors.New("currency not found")
	}
	return nil
}

func (c Currency) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Code)
}

func (c *Currency) Equals(oc *Currency) bool {
	return c.equals(oc)
}
